import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-row justify-between text-center bg-amber-500 py-5 px-10 text-slate-50 font-bold'>
          <Link href='/'>Bird Vision</Link>
          <div>Welcome to E-commerce Site</div>
          <Link href='https://github.com/hakeemsalman'>About Me</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
